// Test generated by RoostGPT for test restAssuredTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

// Test generated for /recipients/branches/{id}_delete for http method type DELETE in rest-assured framework

// RoostTestHash=1ce4bf6e3c

package com.team.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class branches_idDeleteTest {

    // Set base URI before tests start 
    @Before  
    public void setup() {
        RestAssured.baseURI = System.getenv("BASE_URL");
    } 

    @Test
    public void branches_id_delete_Test() {

        // Read CSV file
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\test\\java\\com\\team\\RoostTest\\branches_id_delete.csv"))) {

            String line;
            while ((line = Reader.readLine()) != null) {
                String[] data = line.split(",");

                // Create a map of header to data
                Map<String, String> map = new HashMap<>();
                for (int i = 0; i < data.length; i++) {
                    map.put("id", data[i]);
                }

                // Delete request and response evaluation
                given()
                    .pathParam("id", map.get("id"))
                    .when()
                    .delete("/recipients/branches/{id}")
                    .then()
                    .assertThat()
                    .statusCode(200)
                    .contentType(ContentType.JSON);

            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

