// Test generated by RoostGPT for test restAssuredTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

// Test generated for /credentials/{id}_delete for http method type DELETE in rest-assured framework

// RoostTestHash=f1fc1d06f7

package com.team.RoostTest;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.matcher.RestAssuredMatchers;
import org.apache.http.HttpStatus;
import org.junit.Test;
import java.nio.file.*;
import java.util.stream.*;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class credentials_idDeleteTest {
  
    @Test  
    public void credentials_id_delete_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
      
        // Read CSV file  
        try(Stream<String> lines = Files.lines(Paths.get("src\\test\\java\\com\\team\\RoostTest\\credentials_id_delete.csv"))) {
            Map<String, String> map = new HashMap<>();
            lines.forEach(line -> {
                String[] data = line.split(",");  
                for (int i = 0; i < data.length; i++) {
                    map.put(data[i], data[++i]);
                }
                
                given()
                    .contentType(ContentType.JSON)
                    .pathParam("id", map.get("id"))
                .when()
                    .delete("/credentials/{id}")  
                .then()
                    .assertThat()
                    .statusCode(anyOf(is(HttpStatus.SC_OK), is(HttpStatus.SC_BAD_REQUEST), is(HttpStatus.SC_UNAUTHORIZED))) 
                    .extract().response();
            });
        } catch(IOException ex) {
            ex.printStackTrace();
        }  
    }
}
