// Test generated by RoostGPT for test restAssuredTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

// RoostTestHash=bb9ad621b1

package com.team.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;

public class laureatesGetTest {
  
    @Test  
    public void laureates_get_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src\test\java\com\team\RoostTest\laureates_get.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.pathParam("offset", map.get("offset"))
				.pathParam("limit", map.get("limit"))
				.pathParam("sort", map.get("sort"))
				.pathParam("ID", map.get("ID"))
				.pathParam("name", map.get("name"))
				.pathParam("gender", map.get("gender"))
				.pathParam("motivation", map.get("motivation"))
				.pathParam("affiliation", map.get("affiliation"))
				.pathParam("residence", map.get("residence"))
				.pathParam("birthDate", map.get("birthDate"))
				.pathParam("birthDateTo", map.get("birthDateTo"))
				.pathParam("deathDate", map.get("deathDate"))
				.pathParam("deathDateTo", map.get("deathDateTo"))
				.pathParam("foundedDate", map.get("foundedDate"))
				.pathParam("birthCity", map.get("birthCity"))
				.pathParam("birthCountry", map.get("birthCountry"))
				.pathParam("birthContinent", map.get("birthContinent"))
				.pathParam("deathCity", map.get("deathCity"))
				.pathParam("deathCountry", map.get("deathCountry"))
				.pathParam("deathContinent", map.get("deathContinent"))
				.pathParam("foundedCity", map.get("foundedCity"))
				.pathParam("foundedCountry", map.get("foundedCountry"))
				.pathParam("foundedContinent", map.get("foundedContinent"))
				.pathParam("HeadquartersCity", map.get("HeadquartersCity"))
				.pathParam("HeadquartersCountry", map.get("HeadquartersCountry"))
				.pathParam("HeadquartersContinent", map.get("HeadquartersContinent"))
				.pathParam("nobelPrizeYear", map.get("nobelPrizeYear"))
				.pathParam("yearTo", map.get("yearTo"))
				.pathParam("nobelPrizeCategory", map.get("nobelPrizeCategory"))
				.pathParam("format", map.get("format"))
				.pathParam("csvLang", map.get("csvLang"))
                .when()
                .get("/laureates")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {

            if (response.jsonPath().get("laureates") != null) {
              for (int i = 0; i < response.jsonPath().getList("laureates").size(); i++) {
            if (response.jsonPath().get("laureates[`"+ i +"`].id") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].id"), instanceOf(Integer.class));
                MatcherAssert.assertThat(response.jsonPath().getDouble("laureates[`"+ i +"`].id"), greaterThanOrEqualTo(1));

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.knownName") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.knownName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.knownName.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.knownName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.knownName.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.knownName.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.knownName.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.givenName") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.givenName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.givenName.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.givenName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.givenName.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.givenName.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.givenName.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.familyName") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.familyName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.familyName.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.familyName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.familyName.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.familyName.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.familyName.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.fullName") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.fullName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.fullName.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.fullName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.fullName.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.fullName.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.fullName.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.filename") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.filename"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.penname") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.penname"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.gender") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.gender"), instanceOf(String.class));
                MatcherAssert.assertThat(response.jsonPath().getString("laureates[`"+ i +"`].laureateIfPerson.gender"), anyOf(equalTo("female"), equalTo("male")));

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.date") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.date"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.city") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.city.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.city.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.city.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.city.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.country") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.country.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.country.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.country.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.country.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.cityNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.cityNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.cityNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.cityNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.cityNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.cityNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfPerson.birth.place.cityNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.countryNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.countryNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.countryNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.countryNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.countryNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.countryNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfPerson.birth.place.countryNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.continent") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.continent.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.continent.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.continent.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.continent.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.locationString") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.locationString.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.locationString.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.locationString.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.birth.place.locationString.false"), instanceOf(String.class));
          }

          }

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.date") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.date"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.city") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.city.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.city.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.city.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.city.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.country") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.country.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.country.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.country.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.country.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.cityNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.cityNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.cityNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.cityNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.cityNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.cityNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfPerson.death.place.cityNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.countryNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.countryNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.countryNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.countryNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.countryNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.countryNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfPerson.death.place.countryNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.continent") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.continent.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.continent.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.continent.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.continent.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.locationString") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.locationString.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.locationString.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.locationString.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfPerson.death.place.locationString.false"), instanceOf(String.class));
          }

          }

          }

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.orgName") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.orgName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.orgName.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.orgName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.orgName.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.orgName.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.orgName.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.nativeName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.nativeName"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.acronym") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.acronym"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.date") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.date"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.city") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.city.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.city.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.city.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.city.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.country") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.country.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.country.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.country.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.country.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.cityNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.cityNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.cityNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.cityNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.cityNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.cityNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfOrg.founded.place.cityNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.countryNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.countryNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.countryNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.countryNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.countryNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.countryNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfOrg.founded.place.countryNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.continent") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.continent.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.continent.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.continent.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.continent.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.locationString") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.locationString.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.locationString.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.locationString.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.founded.place.locationString.false"), instanceOf(String.class));
          }

          }

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.date") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.date"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.city") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.city.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.city.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.city.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.city.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.country") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.country.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.country.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.country.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.country.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.cityNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.cityNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.cityNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.cityNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.cityNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.cityNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.cityNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.countryNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.countryNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.countryNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.countryNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.countryNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.countryNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.countryNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.continent") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.continent.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.continent.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.continent.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.continent.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.locationString") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.locationString.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.locationString.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.locationString.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.dissolution.place.locationString.false"), instanceOf(String.class));
          }

          }

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.city") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.city.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.city.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.city.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.city.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.country") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.country.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.country.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.country.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.country.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.cityNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.cityNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.cityNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.cityNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.cityNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.cityNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfOrg.headquarters.cityNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.countryNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.countryNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.countryNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.countryNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.countryNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.countryNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].laureateIfOrg.headquarters.countryNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.continent") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.continent.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.continent.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.continent.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.continent.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.continent.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.continent.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.locationString") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.locationString.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.locationString.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.locationString.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].laureateIfOrg.headquarters.locationString.false"), instanceOf(String.class));
          }

          }

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].wikipedia") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].wikipedia.slug") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].wikipedia.slug"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].wikipedia.english") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].wikipedia.english"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].wikidata") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].wikidata.id") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].wikidata.id"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].wikidata.url") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].wikidata.url"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].sameAs"), instanceOf(List.class));

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].links") != null) {
              for (int i1 = 0; i1 < response.jsonPath().getList("laureates[`"+ i +"`].links").size(); i1++) {
            if (response.jsonPath().get("laureates[`"+ i +"`].links[`"+ i1 +"`].rel") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].links[`"+ i1 +"`].rel"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].links[`"+ i1 +"`].href") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].links[`"+ i1 +"`].href"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].links[`"+ i1 +"`].action") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].links[`"+ i1 +"`].action"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].links[`"+ i1 +"`].types") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].links[`"+ i1 +"`].types"), instanceOf(String.class));
          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].links"), instanceOf(List.class));

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes") != null) {
              for (int i1 = 0; i1 < response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes").size(); i1++) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].awardYear") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].awardYear"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].category") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].category.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].category.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].category.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].category.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].category.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].category.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].categoryFullName") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].categoryFullName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].categoryFullName.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].categoryFullName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].categoryFullName.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].categoryFullName.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].categoryFullName.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].sortOrder") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].sortOrder"), instanceOf(String.class));
                MatcherAssert.assertThat(response.jsonPath().getString("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].sortOrder"), anyOf(equalTo("1"), equalTo("2"), equalTo("3")));

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].portion") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].portion"), instanceOf(String.class));
                MatcherAssert.assertThat(response.jsonPath().getString("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].portion"), anyOf(equalTo("1"), equalTo("1/2"), equalTo("1/3"), equalTo("1/4")));

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].dateAwarded") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].dateAwarded"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].prizeStatus") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].prizeStatus"), instanceOf(String.class));
                MatcherAssert.assertThat(response.jsonPath().getString("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].prizeStatus"), anyOf(equalTo("received"), equalTo("declined"), equalTo("restricted")));

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].motivation") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].motivation.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].motivation.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].motivation.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].motivation.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].motivation.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].motivation.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].prizeAmount") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].prizeAmount"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].prizeAmountAdjusted") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].prizeAmountAdjusted"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations") != null) {
              for (int i11 = 0; i11 < response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations").size(); i11++) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].name") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].name.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].name.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].name.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].name.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].name.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].name.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].nameNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].nameNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].nameNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].nameNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].nameNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].nameNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].nameNow.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].nativeName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].nativeName"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].city") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].city.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].city.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].city.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].city.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].country") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].country.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].country.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].country.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].country.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].cityNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].cityNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].cityNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].cityNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].cityNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].cityNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].cityNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].countryNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].countryNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].countryNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].countryNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].countryNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].countryNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].countryNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].locationString") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].locationString.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].locationString.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].locationString.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations[`"+ i11 +"`].locationString.false"), instanceOf(String.class));
          }

          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].affiliations"), instanceOf(List.class));

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences") != null) {
              for (int i11 = 0; i11 < response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences").size(); i11++) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].city") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].city.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].city.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].city.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].city.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].city.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].city.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].country") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].country.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].country.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].country.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].country.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].country.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].country.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].cityNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].cityNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].cityNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].cityNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].cityNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].cityNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].cityNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].cityNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].cityNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].countryNow") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].countryNow.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].countryNow.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].countryNow.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].countryNow.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].countryNow.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].countryNow.false"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].countryNow.sameAs") != null) {
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].countryNow.sameAs"), instanceOf(List.class));

          }

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].locationString") != null) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].locationString.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].locationString.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].locationString.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].locationString.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].locationString.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences[`"+ i11 +"`].locationString.false"), instanceOf(String.class));
          }

          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].residences"), instanceOf(List.class));

          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links") != null) {
              for (int i11 = 0; i11 < response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links").size(); i11++) {
            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links[`"+ i11 +"`].rel") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links[`"+ i11 +"`].rel"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links[`"+ i11 +"`].href") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links[`"+ i11 +"`].href"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links[`"+ i11 +"`].action") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links[`"+ i11 +"`].action"), instanceOf(String.class));
          }

            if (response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links[`"+ i11 +"`].types") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links[`"+ i11 +"`].types"), instanceOf(String.class));
          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes[`"+ i1 +"`].links"), instanceOf(List.class));

          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("laureates[`"+ i +"`].nobelPrizes"), instanceOf(List.class));

          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("laureates"), instanceOf(List.class));

          }

            if (response.jsonPath().get("meta") != null) {
            if (response.jsonPath().get("meta.offset") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.offset"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("meta.limit") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.limit"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("meta.sort") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.sort"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.ID") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.ID"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("meta.name") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.name"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.gender") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.gender"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.motivation") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.motivation"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.affiliation") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.affiliation"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.residence") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.residence"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.birthDate") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.birthDate"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.birthDateTo") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.birthDateTo"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.deathDate") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.deathDate"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.deathDateTo") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.deathDateTo"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.foundedDate") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.foundedDate"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.birthCity") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.birthCity"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.birthCountry") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.birthCountry"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.birthContinent") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.birthContinent"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.deathCity") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.deathCity"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.deathCountry") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.deathCountry"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.deathContinent") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.deathContinent"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.foundedCity") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.foundedCity"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.foundedCountry") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.foundedCountry"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.foundedContinent") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.foundedContinent"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.headquartersCity") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.headquartersCity"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.headquartersCountry") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.headquartersCountry"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.headquartersContinent") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.headquartersContinent"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.nobelPrizeYear") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.nobelPrizeYear"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("meta.yearTo") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.yearTo"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("meta.nobelPrizeCategory") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.nobelPrizeCategory"), instanceOf(String.class));
          }

            if (response.jsonPath().get("meta.count") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("meta.count"), instanceOf(Integer.class));
          }

          }

            if (response.jsonPath().get("links") != null) {
              for (int i = 0; i < response.jsonPath().getList("links").size(); i++) {
            if (response.jsonPath().get("links[`"+ i +"`].first") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("links[`"+ i +"`].first"), instanceOf(String.class));
          }

            if (response.jsonPath().get("links[`"+ i +"`].prev") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("links[`"+ i +"`].prev"), instanceOf(String.class));
          }

            if (response.jsonPath().get("links[`"+ i +"`].self") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("links[`"+ i +"`].self"), instanceOf(String.class));
          }

            if (response.jsonPath().get("links[`"+ i +"`].next") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("links[`"+ i +"`].next"), instanceOf(String.class));
          }

            if (response.jsonPath().get("links[`"+ i +"`].last") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("links[`"+ i +"`].last"), instanceOf(String.class));
          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("links"), instanceOf(List.class));

          }
}
if (response.statusCode() == 400) {

            if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));
          }

            if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));
          }
}
if (response.statusCode() == 404) {

            if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));
          }

            if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));
          }
}
if (response.statusCode() == 422) {

            if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));
          }

            if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));
          }
}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
