// Test generated by RoostGPT for test restAssuredTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

// RoostTestHash=adfce3f1d2

package com.team.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;

public class nobelPrize_category_yearGetTest {
  
    @Test  
    public void nobelPrize_category_year_get_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src\test\java\com\team\RoostTest\nobelPrize_category_year_get.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.pathParam("category", map.get("category"))
				.pathParam("year", map.get("year"))
                .when()
                .get("/nobelPrize/{category}/{year}")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {

            if (response.jsonPath().get("nobelPrize") != null) {
            if (response.jsonPath().get("nobelPrize.awardYear") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.awardYear"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("nobelPrize.category") != null) {
            if (response.jsonPath().get("nobelPrize.category.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.category.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.category.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.category.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.category.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.category.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("nobelPrize.categoryFullName") != null) {
            if (response.jsonPath().get("nobelPrize.categoryFullName.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.categoryFullName.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.categoryFullName.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.categoryFullName.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.categoryFullName.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.categoryFullName.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("nobelPrize.dateAwarded") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.dateAwarded"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.prizeAmount") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.prizeAmount"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("nobelPrize.prizeAmountAdjusted") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.prizeAmountAdjusted"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("nobelPrize.topMotivation") != null) {
            if (response.jsonPath().get("nobelPrize.topMotivation.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.topMotivation.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.topMotivation.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.topMotivation.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.topMotivation.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.topMotivation.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("nobelPrize.laureates") != null) {
              for (int i = 0; i < response.jsonPath().getList("nobelPrize.laureates").size(); i++) {
            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].id") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].id"), instanceOf(Integer.class));
                MatcherAssert.assertThat(response.jsonPath().getDouble("nobelPrize.laureates[`"+ i +"`].id"), greaterThanOrEqualTo(1));

          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].name") != null) {
            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].name.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].name.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].name.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].name.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].name.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].name.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].portion") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].portion"), instanceOf(String.class));
                MatcherAssert.assertThat(response.jsonPath().getString("nobelPrize.laureates[`"+ i +"`].portion"), anyOf(equalTo("1"), equalTo("1/2"), equalTo("1/3"), equalTo("1/4")));

          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].sortOrder") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].sortOrder"), instanceOf(String.class));
                MatcherAssert.assertThat(response.jsonPath().getString("nobelPrize.laureates[`"+ i +"`].sortOrder"), anyOf(equalTo("1"), equalTo("2"), equalTo("3")));

          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].motivation") != null) {
            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].motivation.en") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].motivation.en"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].motivation.se") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].motivation.se"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].motivation.false") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].motivation.false"), instanceOf(String.class));
          }

          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].links") != null) {
              for (int i1 = 0; i1 < response.jsonPath().getList("nobelPrize.laureates[`"+ i +"`].links").size(); i1++) {
            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].links[`"+ i1 +"`].rel") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].links[`"+ i1 +"`].rel"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].links[`"+ i1 +"`].href") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].links[`"+ i1 +"`].href"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].links[`"+ i1 +"`].action") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].links[`"+ i1 +"`].action"), instanceOf(String.class));
          }

            if (response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].links[`"+ i1 +"`].types") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("nobelPrize.laureates[`"+ i +"`].links[`"+ i1 +"`].types"), instanceOf(String.class));
          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("nobelPrize.laureates[`"+ i +"`].links"), instanceOf(List.class));

          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("nobelPrize.laureates"), instanceOf(List.class));

          }

          }
}
if (response.statusCode() == 400) {

            if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));
          }

            if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));
          }
}
if (response.statusCode() == 404) {

            if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));
          }

            if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));
          }
}
if (response.statusCode() == 422) {

            if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));
          }

            if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));
          }
}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
