// Test generated by RoostGPT for test restAssuredTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

// RoostTestHash=aa0a5d4980

package com.team.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;

public class personsGetTest {
  
    @Test  
    public void persons_get_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src\test\java\com\team\RoostTest\persons_get.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.pathParam("size", map.get("size"))
				.pathParam("offset", map.get("offset"))
				.pathParam("name", map.get("name"))
				.pathParam("birth-date", map.get("birth-date"))
                .when()
                .get("/recipients/persons")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {

            if (response.jsonPath().get("total") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("total"), instanceOf(Integer.class));
          }

            if (response.jsonPath().get("persons") != null) {
              for (int i = 0; i < response.jsonPath().getList("persons").size(); i++) {
            if (response.jsonPath().get("persons[`"+ i +"`].id") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].id"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].initials") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].initials"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].firstName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].firstName"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].middleName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].middleName"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].lastName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].lastName"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].birthDate") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].birthDate"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].birthPlace") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].birthPlace"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].phone") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].phone"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].email") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].email"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].postalCode") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].postalCode"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].houseNumber") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].houseNumber"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].houseNumberPostfix") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].houseNumberPostfix"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].countryCode") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].countryCode"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].reference") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].reference"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].createdAt") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].createdAt"), instanceOf(String.class));
          }

            if (response.jsonPath().get("persons[`"+ i +"`].updatedAt") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("persons[`"+ i +"`].updatedAt"), instanceOf(String.class));
          }

                }
                MatcherAssert.assertThat(response.jsonPath().getList("persons"), instanceOf(List.class));

          }
}
if (response.statusCode() == 400) {
}
if (response.statusCode() == 401) {
}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
