// Test generated by RoostGPT for test roostPostmanTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.team.backend;

import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Controller_createScreen_33abd0691b_Test {

    @Autowired
    private ScreenController screenController;
    
    @MockBean
    private ScreenRepository screenRepository;
    
    @Test
    public void testCreateScreenSuccess() {
        Screen screen = new Screen();
        screen.setName("Screen 1");

        Mockito.when(screenRepository.save(Mockito.any())).thenReturn(screen);  

        Screen result = screenController.createScreen(screen);
        assertNotNull(result);
        assertEquals(screen.getName(), result.getName());
    }
    
    @Test
    public void testCreateScreenFailure() {
        Screen screen = new Screen();
        screen.setName("Screen 1");

        Mockito.when(screenRepository.save(Mockito.any())).thenThrow(new RuntimeException("Test Exception"));

        Exception exception = assertThrows(RuntimeException.class, () -> {
            screenController.createScreen(screen);
        });

        String expectedMessage = "Test Exception";
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.equals(expectedMessage));
    }
}

