// Test generated by RoostGPT for test roostPostmanTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.team.backend;

import org.bson.types.ObjectId;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.*;

import com.team.backend.model.Screen;
import com.team.backend.repository.Repository;

@SpringBootTest
public class Controller_createScreenSeats_8d9f71e8f0_Test {

    @Autowired
    private Controller controller;

    @MockBean
    private Repository repository;

    private Screen screen;

    @BeforeEach
    public void setUp() {
        screen = new Screen();
        screen.set_id(ObjectId.get());
    }

    @Test
    public void testCreateScreenSeatsSuccess() {
        Mockito.when(repository.save(screen)).thenReturn(screen);
        Screen result = controller.createScreenSeats(screen);
        assertNotNull(result);
        assertNotNull(result.get_id());
        assertEquals(screen.get_id(), result.get_id());
    }

    @Test
    public void testCreateScreenSeatsFailure() {
        Mockito.doThrow(new RuntimeException("Exception occurred")).when(repository).save(screen);
        assertThrows(RuntimeException.class, () -> {
            controller.createScreenSeats(screen);
        });
    }
}
