// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-3.5-turbo

package com.team.backend;

import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import javax.validation.Valid;
import java.util.List;

public class Controller_createScreenSeats_8d9f71e8f0_Test {

    @Autowired
    private ScreenRepository repository;

    @Test
    public void testCreateScreenSeats_Success() {
        // TODO: Mock the request body for a successful scenario
        Screen screens = new Screen();

        Screen result = createScreenSeats(screens);

        // TODO: Assert the expected output with the actual output
        Assert.assertEquals(result, screens);
    }

    @Test
    public void testCreateScreenSeats_Failure() {
        // TODO: Mock the request body for a failure scenario
        Screen screens = new Screen();

        Screen result = createScreenSeats(screens);

        // TODO: Assert the expected output with the actual output
        Assert.assertNotEquals(result, screens);
    }

    private Screen createScreenSeats(@Valid @RequestBody Screen screens) {
        screens.set_id(ObjectId.get());
        repository.save(screens);
        return screens;
    }
}
