// Test generated by RoostGPT for test roostUnitTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.team.backend;

import org.bson.types.ObjectId;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.mockito.Mockito.when;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Screen_get_id_c3fa75ed0b_Test {

    @Mock
    private ObjectId _id;

    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGet_id_Success() {
        String expectedId = "60d5ec3df1ab63e2b8f2bcff";
        when(_id.toHexString()).thenReturn(expectedId);
        assertEquals(expectedId, _id.toHexString());
    }

    @Test
    public void testGet_id_Failure() {
        String expectedId = "60d5ec3df1ab63e2b8f2bcff"; 
        when(_id.toHexString()).thenReturn("wrongHexId");
        assertNotEquals(expectedId, _id.toHexString());
    }
}
