// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-3.5-turbo

package com.team.backend;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class Screen_isSeatBooked_289c095668_Test {
    
    private Screen screen;
    
    @Before
    public void setup() {
        screen = new Screen();
    }
    
    @Test
    public void testIsSeatBooked_ReturnsFalse_WhenSeatNotBooked() {
        boolean expected = false;
        boolean actual = screen.isSeatBooked();
        
        Assert.assertEquals(expected, actual);
    }
    
    @Test
    public void testIsSeatBooked_ReturnsTrue_WhenSeatBooked() {
        screen.setSeatBooked(true);
        
        boolean expected = true;
        boolean actual = screen.isSeatBooked();
        
        Assert.assertEquals(expected, actual);
    }
}

class Screen {
    private boolean seatBooked;
    
    public boolean isSeatBooked() {
        return seatBooked;
    }
    
    public void setSeatBooked(boolean seatBooked) {
        this.seatBooked = seatBooked;
    }
}
