// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-3.5-turbo

package com.team.backend;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class Screen_getScreenName_f8aab6599c_Test {

    private Screen screen;

    @BeforeClass
    public void setUp() {
        screen = new Screen();
    }

    @Test
    public void testGetScreenName() {
        String expectedScreenName = "Test Screen";
        screen.setScreenName(expectedScreenName);

        String actualScreenName = screen.getScreenName();

        Assert.assertEquals(actualScreenName, expectedScreenName);
    }

    @Test
    public void testGetScreenName_Null() {
        String expectedScreenName = null;
        screen.setScreenName(expectedScreenName);

        String actualScreenName = screen.getScreenName();

        Assert.assertEquals(actualScreenName, expectedScreenName);
    }
}

class Screen {
    private String screenName;

    public String getScreenName() {
        return screenName;
    }

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }
}
