// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-3.5-turbo

package com.team.backend;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import java.util.ArrayList;

public class Screen_isSeatBooked_289c095668_Test {

    @Id
    private ObjectId id;
    private boolean seatBooked;

    public boolean isSeatBooked() {
        return seatBooked;
    }

    // Test case 1: Seat is booked
    @Test
    public void testIsSeatBooked_WhenSeatIsBooked_ReturnsTrue() {
        // Arrange
        Screen screen = new Screen();
        screen.setSeatBooked(true);

        // Act
        boolean result = screen.isSeatBooked();

        // Assert
        assertTrue(result);
    }

    // Test case 2: Seat is not booked
    @Test
    public void testIsSeatBooked_WhenSeatIsNotBooked_ReturnsFalse() {
        // Arrange
        Screen screen = new Screen();
        screen.setSeatBooked(false);

        // Act
        boolean result = screen.isSeatBooked();

        // Assert
        assertFalse(result);
    }
}
