// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-3.5-turbo

package com.team.backend;

import org.junit.Assert;
import org.junit.Test;

public class Screen_setScreenName_f759fd1684_Test {

    @Test
    public void testSetScreenName_Success() {
        // Given
        Screen screen = new Screen();
        String expectedScreenName = "Home";

        // When
        screen.setScreenName(expectedScreenName);

        // Then
        Assert.assertEquals(expectedScreenName, screen.getScreenName());
    }

    @Test
    public void testSetScreenName_NullInput() {
        // Given
        Screen screen = new Screen();
        String expectedScreenName = null;

        // When
        screen.setScreenName(expectedScreenName);

        // Then
        Assert.assertNull(screen.getScreenName());
    }
}

class Screen {
    private String screenName;

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    public String getScreenName() {
        return screenName;
    }
}
