// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-3.5-turbo

package com.team.backend;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.awaitility.Awaitility.await;
import static org.hamcrest.Matchers.equalTo;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Screen_setSeatBooked_446a113875_Test {

    @Mock
    private Screen screen;

    @Test
    public void testSetSeatBooked_True() {
        screen.setSeatBooked(true);

        await().until(() -> screen.isSeatBooked(), equalTo(true));
    }

    @Test
    public void testSetSeatBooked_False() {
        screen.setSeatBooked(false);

        await().until(() -> screen.isSeatBooked(), equalTo(false));
    }
}
