// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-3.5-turbo

package com.team.backend;

import org.bson.types.ObjectId;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class Screen_get_id_c3fa75ed0b_Test {

    @Test
    public void testGetId_Success() {
        // Arrange
        ObjectId objectId = new ObjectId();
        Screen screen = new Screen(objectId);

        // Act
        String actualId = screen.get_id();

        // Assert
        Assertions.assertEquals(objectId.toHexString(), actualId);
    }

    @Test
    public void testGetId_NullId() {
        // Arrange
        Screen screen = new Screen(null);

        // Act
        String actualId = screen.get_id();

        // Assert
        Assertions.assertNull(actualId);
    }
}

class Screen {
    @Id
    private ObjectId _id;

    public Screen(ObjectId _id) {
        this._id = _id;
    }

    public String get_id() {
        return _id != null ? _id.toHexString() : null;
    }
}
