// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-3.5-turbo

package com.team.backend;

import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayList;

public class Screen_getSeats_d4e6eecacd_Test {

    @Test
    public void testGetSeats_Success() {
        // Arrange
        Screen screen = new Screen();
        ArrayList<String> expectedSeats = new ArrayList<>();
        expectedSeats.add("A1");
        expectedSeats.add("A2");
        expectedSeats.add("A3");
        screen.setSeats(expectedSeats);

        // Act
        ArrayList<String> actualSeats = screen.getSeats();

        // Assert
        Assert.assertEquals(expectedSeats, actualSeats);
    }

    @Test
    public void testGetSeats_EmptySeats() {
        // Arrange
        Screen screen = new Screen();
        ArrayList<String> expectedSeats = new ArrayList<>();

        // Act
        ArrayList<String> actualSeats = screen.getSeats();

        // Assert
        Assert.assertEquals(expectedSeats, actualSeats);
    }
}
