// Test generated by RoostGPT for test roostPostmanTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.team.backend;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Screen_isSeatBooked_289c095668_Test {

    @Test
    public void testIsSeatBooked() {
        Screen screen = new Screen();
        screen.setSeatBooked(true);
        Assertions.assertTrue(screen.isSeatBooked());
    }

    @Test
    public void testIsSeatNotBooked() {
        Screen screen = new Screen();
        screen.setSeatBooked(false);
        Assertions.assertFalse(screen.isSeatBooked());
    }
}
