// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.team.backend;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Screen_setSeatBooked_446a113875_Test {

    @Mock
    private Screen screen;

    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetSeatBooked_True() {
        screen.setSeatBooked(true);
        Assert.assertTrue(screen.isSeatBooked());
    }

    @Test
    public void testSetSeatBooked_False() {
        screen.setSeatBooked(false);
        Assert.assertFalse(screen.isSeatBooked());
    }
}
