// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-3.5-turbo

package com.team.backend;

import org.junit.Assert;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;

public class Screen_setSeatBooked_446a113875_Test {

    private Screen screen;

    @Given("^a screen with seat booked status$")
    public void a_screen_with_seat_booked_status() {
        screen = new Screen();
        screen.setSeatBooked(true);
    }

    @When("^the seat booked status is set to false$")
    public void the_seat_booked_status_is_set_to_false() {
        screen.setSeatBooked(false);
    }

    @Then("^the seat booked status should be false$")
    public void the_seat_booked_status_should_be_false() {
        Assert.assertFalse(screen.isSeatBooked());
    }

    @Given("^a screen with seat not booked status$")
    public void a_screen_with_seat_not_booked_status() {
        screen = new Screen();
        screen.setSeatBooked(false);
    }

    @When("^the seat booked status is set to true$")
    public void the_seat_booked_status_is_set_to_true() {
        screen.setSeatBooked(true);
    }

    @Then("^the seat booked status should be true$")
    public void the_seat_booked_status_should_be_true() {
        Assert.assertTrue(screen.isSeatBooked());
    }

    private class Screen {
        private boolean seatBooked;

        public boolean isSeatBooked() {
            return seatBooked;
        }

        public void setSeatBooked(boolean seatBooked) {
            this.seatBooked = seatBooked;
        }
    }
}
